# Generated by Django 5.2.7 on 2025-10-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(help_text='Ejemplo: kg, g, pieza, litro', max_length=20)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='img_productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='app_productos.producto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
